/*
=========================================================
Project: AdventureWorks Sales Analytics
Analysis: Revenue at Risk From Lost Customers
=========================================================

Business Question:
How much revenue did the company lose from customers
who purchased in 2024 but did not purchase in 2025?

Business Definition:
Lost Customer = Customer purchased in 2024 but had no
                purchase in 2025.

Revenue at Risk = Total 2024 revenue generated by
                  customers who were lost in 2025.

Analysis Period:
2024 → 2025

Metrics:
- Total Lost Customers
- Total Revenue at Risk
- Average Revenue per Lost Customer

Business Purpose:
Quantify the financial impact of customer churn and
identify the potential revenue exposure associated with
lost customers.

Assumptions:
- A customer is considered lost if they purchased at least
  once in 2024 and made no purchase in 2025.
- Revenue is calculated using TotalDue.
- Revenue at risk represents the lost customers' previous-
  year revenue; it does not mean the exact future revenue
  that would have been generated.

=========================================================
*/

WITH Customer2024 AS
(
    SELECT
        CustomerID,
        'Purchased' AS Order2024
    FROM Sales.SalesOrderHeader
    WHERE YEAR(OrderDate) = 2024
    GROUP BY CustomerID
),

Customer2025 AS
(
    SELECT
        CustomerID,
        'Purchased' AS Order2025
    FROM Sales.SalesOrderHeader
    WHERE YEAR(OrderDate) = 2025
    GROUP BY CustomerID
),
LostCustomers as
(
SELECT
    C24.CustomerID,
    C24.Order2024,
    C25.Order2025
FROM Customer2024 AS C24
LEFT JOIN Customer2025 AS C25
    ON C24.CustomerID = C25.CustomerID
WHERE C25.CustomerID IS NULL
),
Customer2024andTotal as
(
Select CustomerID,
       Sum(Totaldue) as TotalDue
From Sales.SalesOrderHeader where Year(OrderDate) = 2024
group by CustomerID
),
LostcustomerwithTotal as
(
Select LC.CustomerID,
       TotalDue
from LostCustomers as LC inner join Customer2024andTotal as CT on LC.CustomerID = CT.CustomerID
)

Select Count(CustomerID) Total_Lost_Customer,
       Sum(TotalDue) as Total_lost_Customer_Revenue,
       AVg(TotalDue) as AvgRevenuePerLostCustomer
from LostcustomerwithTotal

