/*
=========================================================
Project: AdventureWorks Sales Analytics
Analysis: Revenue at Risk From Lost Customers
=========================================================

Business Question:
How much revenue did the company put at risk from
customers who purchased in 2024 but did not purchase
in 2025?

Business Definition:
Lost Customer = Customer purchased in 2024 but had no
                purchase in 2025.

Revenue at Risk = Total 2024 revenue generated by
                  lost customers.

Analysis Period:
2024 → 2025

Metrics:
- Total Lost Customers
- Total Revenue at Risk
- Average Revenue per Lost Customer

Business Purpose:
Quantify the financial impact associated with customer
churn and identify the potential revenue exposure from
lost customers.

Assumptions:
- A customer is considered lost if they purchased at
  least once in 2024 and made no purchase in 2025.
- Revenue is calculated using TotalDue.
- Revenue at risk represents previous-year revenue and
  does not guarantee future revenue loss.

=========================================================
*/

-- =====================================================
-- SQL Analysis
-- =====================================================

WITH Customer2024 AS
(
    SELECT
        CustomerID,
        'Purchased' AS Order2024
    FROM Sales.SalesOrderHeader
    WHERE YEAR(OrderDate) = 2024
    GROUP BY CustomerID
),

Customer2025 AS
(
    SELECT
        CustomerID,
        'Purchased' AS Order2025
    FROM Sales.SalesOrderHeader
    WHERE YEAR(OrderDate) = 2025
    GROUP BY CustomerID
),

LostCustomers AS
(
    SELECT
        C24.CustomerID,
        C24.Order2024,
        C25.Order2025
    FROM Customer2024 AS C24
    LEFT JOIN Customer2025 AS C25
        ON C24.CustomerID = C25.CustomerID
    WHERE C25.CustomerID IS NULL
),

Customer2024andTotal AS
(
    SELECT
        CustomerID,
        SUM(TotalDue) AS TotalDue
    FROM Sales.SalesOrderHeader
    WHERE YEAR(OrderDate) = 2024
    GROUP BY CustomerID
),

LostCustomerWithTotal AS
(
    SELECT
        LC.CustomerID,
        CT.TotalDue
    FROM LostCustomers AS LC
    INNER JOIN Customer2024andTotal AS CT
        ON LC.CustomerID = CT.CustomerID
)

SELECT
    COUNT(CustomerID) AS TotalLostCustomers,
    SUM(TotalDue) AS TotalRevenueAtRisk,
    AVG(TotalDue) AS AvgRevenuePerLostCustomer
FROM LostCustomerWithTotal;


/*
=========================================================
Results
=========================================================

Total Lost Customers:
8,363

Total Revenue at Risk:
10,621,100.50

Average Revenue per Lost Customer:
1,270.01

=========================================================
Business Insight
=========================================================

8,363 customers who purchased in 2024 did not purchase
in 2025. These lost customers generated approximately
10.62M in 2024 revenue, representing significant
revenue at risk.

The average revenue generated per lost customer was
approximately 1,270.

=========================================================
CEO Action
=========================================================

The CEO can prioritize win-back campaigns for lost
customers, particularly customers with historically high
revenue. Further segmentation by customer revenue can
help identify which lost customers should receive the
highest retention priority.

=========================================================
Important Interpretation
=========================================================

Revenue at risk represents the previous-year revenue
generated by lost customers. It should not be interpreted
as guaranteed future revenue loss.

=========================================================
*/
