/*
=========================================================
Project: AdventureWorks Sales Analytics
Analysis: Customer Revenue Concentration
=========================================================

Business Question:
What percentage of total company revenue is generated
by the top 20% of customers?

Business Definition:
Top 20% Customers = Customers ranked in the top 20%
based on lifetime revenue.

Revenue Concentration =
Revenue generated by the top 20% of customers
divided by total company revenue.

Metrics:
- Total Customers
- Top 20% Customer Count
- Top 20% Customer Revenue
- Total Company Revenue
- Revenue Contribution of Top 20%

Business Purpose:
Measure the company's dependence on its highest-value
customers and identify potential customer concentration
risk.

Assumptions:
- Customer revenue is calculated using TotalDue.
- Lifetime revenue includes all available sales history.
- ROW_NUMBER() is used to select exactly 20% of customers.

=========================================================
*/

-- =====================================================
-- SQL Analysis
-- =====================================================

WITH CustomerRevenue AS
(
    SELECT
        CustomerID,
        SUM(TotalDue) AS CustomerRevenue
    FROM Sales.SalesOrderHeader
    GROUP BY CustomerID
),

CompanyRevenue AS
(
    SELECT
        SUM(TotalDue) AS CompanyRevenue
    FROM Sales.SalesOrderHeader
),

TotalCustomerCount AS
(
    SELECT
        COUNT(DISTINCT CustomerID) AS TotalCustomers
    FROM Sales.SalesOrderHeader
),

Top20CustomerCount AS
(
    SELECT
        CEILING(TotalCustomers * 0.20) AS Top20Customer
    FROM TotalCustomerCount
),

RevenueRank AS
(
    SELECT
        CustomerID,
        CustomerRevenue,
        ROW_NUMBER() OVER
        (
            ORDER BY CustomerRevenue DESC
        ) AS CustomerRank
    FROM CustomerRevenue
),

Top20Customers AS
(
    SELECT
        COUNT(CustomerID) AS Top20CustomerCount,
        SUM(CustomerRevenue) AS Top20Revenue
    FROM RevenueRank
    CROSS JOIN Top20CustomerCount
    WHERE CustomerRank <= Top20Customer
)

SELECT
    CC.TotalCustomers,
    T20.Top20CustomerCount,
    T20.Top20Revenue,
    CR.CompanyRevenue,
    CAST(
        T20.Top20Revenue * 100.0 / CR.CompanyRevenue
        AS DECIMAL(10,2)
    ) AS RevenueContributionPercentage
FROM Top20Customers AS T20
CROSS JOIN CompanyRevenue AS CR
CROSS JOIN TotalCustomerCount AS CC;


/*
=========================================================
Results
=========================================================

Total Customers:
9,780

Top 20% Customer Count:
3,824

Revenue Contribution from Top 20%:
89.75%

=========================================================
Business Insight
=========================================================

The top 20% of customers contribute approximately 89.75%
of total company revenue, indicating a high concentration
of revenue among a relatively small group of customers.

=========================================================
CEO Action
=========================================================

The CEO should prioritize retention and relationship
management for high-value customers because losing a
small number of these customers could have a significant
impact on company revenue.

The business should also investigate opportunities to
increase revenue from the remaining 80% of customers to
reduce dependency on the highest-value customer segment.

=========================================================
Important Interpretation
=========================================================

This analysis measures revenue concentration, not profit
concentration. The 89.75% figure represents revenue
generated by the top 20% of customers.

=========================================================
*/
